### PR TITLE
fix(server): use existing subscription if it already exists

### LINKED ISSUE #42: Subscriptions created from a naming strategy will fail if they already exist
**Describe the bug**
Subscriptions resolved from naming strategies will fail if the subscription name already exists

**To Reproduce**
1. Create a handler that will use the subscription naming strategy (i.e., just supply a topic name)
2. Start the server and it will create the subscription
3. Restart the server and it will fail as the subscription already exists.

**Expected behavior**
If the subscription already exists, it should be used.

### PR DESCRIPTION
**Pull request by william-reynolds-flosports**
When subscription names aren't provided, and the name is
generated by a `SubscriptionNamingStrategy`, an error will occur if
the subscription already exists. In order to prevent duplication of
effort, I refactored the
`GooglePubSubTransport#getSubscriptionFromPattern` method to
delegate different concerns to other private methods. Later, these
methods could be extracted into separate classes to simplify testing.

resolves #42

### CODE REVIEW

**Comment by william-reynolds-flosports** [comment]
@haroldwaters this conflicts with your changes heavily. Feel free to merge your stuff first and I'll square away the conflicts.

File: lib/server/server-google-pubsub.ts [hunk 1]
```diff
@@ -137,54 +137,98 @@ export class GooglePubSubTransport extends Server implements CustomTransportStra
...
+    private getSubscriptionName = (
+        metadata: GooglePubSubPatternMetadata,
+        pattern: string,
+    ): string => {
+        const _topicName = metadata.topicName;
+        const _subscriptionName = metadata.subscriptionName;
 
-        if (metadata == null || !(metadata.subscriptionName || metadata.topicName)) {
+        const subscriptionName: string | null = _topicName
+            ? this.subscriptionNamingStrategy.generateSubscriptionName(
```
Comment (haroldwaters) [inline lib/server/server-google-pubsub.ts:183]: Do we want to automatically overwrite the subscription name if a topic name is provided? I'm thinking that a subscription is either _always_ passed through the generator or only if only a topic is provided.

File: lib/server/server-google-pubsub.ts [hunk 2]
```diff
@@ -137,54 +137,98 @@ export class GooglePubSubTransport extends Server implements CustomTransportStra
...
+     *
+     * @remarks
+     * If PubSub Client cannot create the subscription, or if the application is not configured to
+     * create subscriptions, this method will return null when the subscription does not already
+     * exist.
+     *
+     * @throws InvalidPatternMetadataException
+     * Thrown if attempting to create a subscription, but a topic name is not provided.
+     */
+    private getSubscription = async (
```
Comment (haroldwaters) [inline lib/server/server-google-pubsub.ts:209]: `getOrCreate`?

File: lib/server/server-google-pubsub.ts (hunk 1 above)
Comment (haroldwaters) [reply lib/server/server-google-pubsub.ts:183]: Thinking on this some more - I think the behavior should be that the subscription name and/or topic name are both computed before we do any action with them. The basic strategies can just pass the names through if they're already set, but a supplied strategy could alter them.

Comment (william-reynolds-flosports) [reply lib/server/server-google-pubsub.ts:183]: That sounds good to me. Makes sense. Definitely the simplest behavior. I'll implement that.

File: lib/server/server-google-pubsub.ts (hunk 2 above)
Comment (william-reynolds-flosports) [reply lib/server/server-google-pubsub.ts:209]: Good call. Adding that.

File: lib/interfaces.ts [hunk 3]
```diff
@@ -41,7 +41,38 @@ export interface GooglePubSubTransportOptions {
     nackStrategy?: NackStrategy;
 }
 
-export type GenerateSubscriptionName = (topicName: string, subscriptionName?: string) => string;
+export interface TopicNameOnly {
+    _tag: 'TopicNameOnly';
```
Comment (haroldwaters) [inline lib/interfaces.ts:45]: Can this be split into an enum?

File: lib/interfaces.ts [hunk 4]
```diff
@@ -41,7 +41,38 @@ export interface GooglePubSubTransportOptions {
...
+ * possible combinations of subscription and topic names.
+ *
+ * @see BasicSubscriptionNamingStrategy
+ */
+export type SubscriptionNameDependencies =
+    | TopicNameOnly
+    | SubscriptionNameOnly
+    | TopicAndSubscriptionNames;
+
+export type GenerateSubscriptionName = (deps: SubscriptionNameDependencies) => string;
```
Comment (haroldwaters) [inline lib/interfaces.ts:75]: Do any changes need to be made to topic strategy to keep up with this?

**Review by haroldwaters — COMMENTED** [review]
Update the examples in the README as well, please.

File: lib/interfaces.ts (hunk 3 above)
Comment (william-reynolds-flosports) [reply lib/interfaces.ts:45]: Yes.

File: lib/interfaces.ts (hunk 4 above)
Comment (william-reynolds-flosports) [reply lib/interfaces.ts:75]: The topic strategy can remain as is if we want. I don't think it would benefit from any of this since it requires a single required string argument. I'm not sure there would be any benefit to making it optional either.

**Review by bexux — APPROVED** [review]
Code makes sense - tests look good.

File: lib/interfaces.ts (hunk 3 above)
Comment (william-reynolds-flosports) [reply lib/interfaces.ts]: Done!

File: lib/server/server-google-pubsub.ts (hunk 2 above)
Comment (william-reynolds-flosports) [reply lib/server/server-google-pubsub.ts]: Added.

**Review by haroldwaters — APPROVED** [review]
